# Dataframe

When we combine multiple series together then it is called dataframe

In [5]:
import numpy as np
import pandas as pd

### Dataframe using dictionary

In [6]:
data = {
    "name": ["John", "Research", "Ram", "Sita"],
    "age": [25, 22, 30, 28],
    "city": ["New York", "Bharatpur", "Kathmandu", "Pokhara"],
    "salary": [50000, 45000, 60000, 55000]
}

In [7]:
pd.DataFrame(data)

       name  age       city  salary
0      John   25   New York   50000
1  Research   22  Bharatpur   45000
2       Ram   30  Kathmandu   60000
3      Sita   28    Pokhara   55000

### Dataframe using list

In [23]:
data = [
    ["John", "New York", 25, 60000],
    ["Research", "Bharatpur", 22, 45000],
    ["Ram", "Kathmandu", 30, 60000],
    ["Sita", "Pokhara", 28, 55000]
]

In [27]:
columns =  ["Name", "City", "Age", "Salary"]
df2 = pd.DataFrame(data, columns=columns)

### Selection and indexing of column

 - For selection and indexing, we dont use index like [0], [1] etc we use column or header name like ["Name"], ["City"] or for selecting multiple column we use array of aaray like [["Name", "Column"]]

In [16]:
df2["City"]

df2[["Name", "City"]]

       Name       City
0      John   New York
1  Research  Bharatpur
2       Ram  Kathmandu
3      Sita    Pokhara

### Adding new column

In [ ]:
df2["Designation"] = ["Doctor", "engineer", "Doctor", "engineer"]
print(df2)

       Name       City
0      John   New York
1  Research  Bharatpur
2       Ram  Kathmandu
3      Sita    Pokhara

### Remove column

In [36]:
df2.drop(["Age", "Salary"], axis = 1)

       Name       City
0      John   New York
1  Research  Bharatpur
2       Ram  Kathmandu
3      Sita    Pokhara

### Selection of row

In [ ]:
df2.loc[0] # loc is location which is used to selecting data from row

Name         Sita
City      Pokhara
Age            28
Salary      55000
Name: 3, dtype: object

### Selecting subsets of rows and columns

In [45]:
print(df2)
df2.loc[[2, 3]][["Name", "City"]]

       Name       City  Age  Salary
0      John   New York   25   60000
1  Research  Bharatpur   22   45000
2       Ram  Kathmandu   30   60000
3      Sita    Pokhara   28   55000

   Name       City
2   Ram  Kathmandu
3  Sita    Pokhara

### Conditional selection

In [58]:
print(df2)
print("\n", df2[df2["Age"] > 22])

print("\n", df2[(df2["Age"] > 22) & (df2["City"] == "Kathmandu")])
print("\n", df2[(df2["Age"] > 22) | (df2["City"] == "Kathmandu")])

       Name       City  Age  Salary
0      John   New York   25   60000
1  Research  Bharatpur   22   45000
2       Ram  Kathmandu   30   60000
3      Sita    Pokhara   28   55000

    Name       City  Age  Salary
0  John   New York   25   60000
2   Ram  Kathmandu   30   60000
3  Sita    Pokhara   28   55000

   Name       City  Age  Salary
2  Ram  Kathmandu   30   60000

    Name       City  Age  Salary
0  John   New York   25   60000
2   Ram  Kathmandu   30   60000
3  Sita    Pokhara   28   55000