In [1]:
import numpy as np
import pandas as pd

In [12]:
data = {
    "A": [1, 2, np.nan, 4, 5],
    "B": [1, 2, 3, 4, 5],
    "C": [1, 2, 3, np.nan, np.nan],
    "D": [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

### Finding missing data

In [ ]:
df.isna() # check whether row contains NaN value or not. If contains, it will true if not, it will false

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [7]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
df.isna().any() # check whether any column contains null value

A    True
B    True
C    True
D    True
dtype: bool

### Drop the row if it contains missing data

In [ ]:
# Drop a NaN value. It drop on the basis of row. 
# If any NaN value contains by row, then it will remove that row completely 

df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [17]:
# thresh = 3 means don't remove the row if it contains three not NaN value
df.dropna(thresh=2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

### Filling the missing data

In [ ]:

# it will not do any changes in the original data frame unless we add inplace = true
df.fillna(0) # it is column wise

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

### Filling missing data accoring to column

In [ ]:
values = {"A": 0, "B": 100, "C": 300, "D": 400}
df.fillna(value=values) # it is column wise

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [23]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0